//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public double TimeInGame { get; set; }
        public double TimeInLeaderboard { get; set; }
        public int EatedPlayer { get; set; }
        public int MassRecord { get; set; }
        public int GotSkins { get; set; }
        public int Coins { get; set; }
        public int Level { get; set; }
    
        public virtual User User { get; set; }
    }
}
