//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Models.SecondNamespace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Password
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Passwort { get; set; }
        public bool Deleted { get; set; }
    
        public virtual User User { get; set; }
    }
}
