//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Models.SecondNamespace
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestSiteEntities2 : DbContext
    {
        public TestSiteEntities2()
            : base("name=TestSiteEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Email> Email { get; set; }
        public virtual DbSet<Kennwort> Kennwort { get; set; }
        public virtual DbSet<Password> Password { get; set; }
        public virtual DbSet<Salt> Salt { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
